name: build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          git clone https://${GEOIP_TOKEN}@github.com/${GITHUB_REPOSITORY}
          cd log
          go test -v
      - name: Benchmark
        run: |
          cat log/README.md | awk '{if($0 ~ "// go test -v -run=none"){a=1;b=1};if($0 ~ "```" && b=1){b=0};if (a&&b) {print}}' > log_test.go
          go get github.com/phuslu/log
          go get github.com/rs/zerolog
          go get github.com/sirupsen/logrus
          go get go.uber.org/zap
          go test -v -run=none -bench=. -benchtime=10s -benchmem log_test.go

