name: go-slog

on:
  push:
    branches:
      - master

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          check-latest: true
      - uses: actions/checkout@v4
      - name: Verify
        working-directory: ./go-slog
        run: go test -v -args -useWarnings creator.go verify_test.go
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          check-latest: true
      - uses: actions/checkout@v4
      - name: Benchmark
        working-directory: ./go-slog
        run: go test -v -bench=. creator.go bench_test.go
